#Configuración de base de datos SIGVET
#Mon Jun 01 11:53:32 ART 2026
db.password=sigvet123
db.url=jdbc\:mysql\://localhost\:3306/sigvet?useSSL\=false&serverTimezone\=America/Argentina/Buenos_Aires&allowPublicKeyRetrieval\=true
db.usuario=root
